// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/portfolio/:portfolioType": {
    params: {
      "portfolioType": string;
    };
  };
  "/resume": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/portfolio/:portfolioType" | "/resume";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio/:portfolioType";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume";
  };
};